### ISSUE TITLE
日报投稿 - 2019-03-12

### ISSUE THREAD

**Issue by ice1000** [RustStudy/rust_daily_news#11]
https://github.com/pest-parser/intellij-pest

Pest的IntelliJ插件，有rule的补全，补全的时候有hint，有重命名（有点bug，马上有个PR修复），自动高亮`#[grammar_inline = "..."]`里面的Pest代码。
支持Ctrl+Alt+N进行inline和Ctrl+Alt+M进行提取。

**Comment by ZhangHanDong** [comment]
收到
