### ISSUE TITLE
日报投稿 - 2019-04-08 

### ISSUE THREAD

**Issue by xiaohulu** [RustStudy/rust_daily_news#12]
# BlockLang Installer

BlockLang Installer 是一款自动化安装工具，专用于部署 Spring boot 项目。

源代码托管在 <https://github.com/blocklang/blocklang-installer>

BlockLang Installer 安装在应用服务器上，支持：
1. 下载 JDK 和 Spring boot Jar 文件；
2. 安装 JDK；
3. 启动 Spring boot Jar。

功能示意图

![功能示意图](https://raw.githubusercontent.com/blocklang/blocklang-installer/master/images/installer.png)

**Comment by ZhangHanDong** [comment]
@xiaohulu good

**Comment by ZhangHanDong** [comment]
已收录

**Comment by xiaohulu** [comment]
@ZhangHanDong 谢谢。
