### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by pickfire** [RustStudy/rust_daily_news#13]
躲避游戏，避开虫子，获取分数，使用 ggez 框架， Hackathon 时写的，之后会在 rust-malaysia 写文章。

https://github.com/pickfire/bugs

![img](https://user-images.githubusercontent.com/4687791/56095420-5261ef00-5ecc-11e9-8e74-3ef44d4cce77.png)

**Comment by ZhangHanDong** [comment]
good

**Comment by ZhangHanDong** [comment]
之后文章写好也可以在这贴个链接
