### ISSUE TITLE
日报投稿 - 2019-5-13

### ISSUE THREAD

**Issue by readlnh** [RustStudy/rust_daily_news#16]
# [教程]如何用rust为redis写一个client
主要讲解了如何通过RESP实现一个redis client，并用rust实现了一个简单的demo，目前只实现了set和get命令，可以很方便的添加命令，项目地址如下[redis-simple-rs](https://github.com/readlnh/redis-simple-rs.git)欢迎大家完善

**Comment by ZhangHanDong** [comment]
@readlnh 收到，感谢投递
