### ISSUE TITLE
日报投稿： 2019-01-12

### ISSUE THREAD

**Issue by DCjanus** [RustStudy/rust_daily_news#4]
Rust编写的命令行十六进制查看器: <https://github.com/sharkdp/hexyl>

![default](https://user-images.githubusercontent.com/15802727/51040146-a9b4a280-15f1-11e9-9be9-60f4b9d278e1.png)

常数做泛型参数的feature开始实现了: <https://github.com/rust-lang/rust/pull/53645#issuecomment-451706747>

**Comment by damody** [comment]
Timely Dataflow 將其下的git移動到github了
[Frank McSherry](https://github.com/frankmcsherry)是這系列庫的主要作者。
其下的四個庫
[timely-dataflow](https://github.com/TimelyDataflow/timely-dataflow)
用於管理和執行數據並行數據流計算的框架。
[differential-dataflow](https://github.com/TimelyDataflow/differential-dataflow)
對一個圖(graph)，不是圖片是圖論的圖去做差分運算，也能統計圖跟圖之前的變化，
用於輔助timely-dataflow的計算。
[abomonation](https://github.com/TimelyDataflow/abomonation)
一個追求簡單快速但unsafe的序列化程式庫
[Naiad](https://github.com/TimelyDataflow/Naiad)
是timely-dataflow的C#實作品，從微軟研究院fork過來，但沒有做任何改動。

https://github.com/TimelyDataflow
[原文](https://twitter.com/frankmcsherry/status/1083675037629067265)
[可參考 2018-5-21的新聞](https://rust.cc/article/65ba7294-5a76-46f1-932b-286b94f20379)

**Comment by damody** [comment]
dness
一個動態的dns客戶端
當你有一個Server架在家裡，使用動態IP每天跑來跑去時，可以使用。
可以使用這個程式登入 cloudflare ，此程式會在你改變IP時改動你的cloudflare DNS IP。

[原文](https://www.reddit.com/r/rust/comments/aev3h1/dness_a_dynamic_dns_client/)

**Comment by damody** [comment]
#AoC
Hindsight on Advent of Code 2018
此篇作者分享了AoC挑戰中他的解決方法，值得一讀。值得一讀。值得一讀。

[原文](https://phaazon.net/blog/aoc-18-hindsight)

**Comment by ZhangHanDong** [comment]
@DCjanus @damody 收到

**Comment by Linger2** [comment]
### Rust 官博发文征求Rust 2019 Roadmap

征求各位关于：

* 社区计划的想法
* Language features
* 文档上的改进
* 生态系统需要
* 工具加强
* 还有一些你希望在2019 Rust上看到的东西

原文地址：[A call for Rust 2019 Roadmap blog posts](https://blog.rust-lang.org/2018/12/06/call-for-rust-2019-roadmap-blogposts.html)

一些关于Rust 2019 Roadmap的文章可以在这个上面找到：[Read More](https://readrust.net/rust-2019/)

### RustWasm 也发文征求2019 Roadmap

[Reflecting on Rust and WebAssembly in 2018](https://rustwasm.github.io/2018/12/06/reflecting-on-rust-and-wasm-in-2018.html)

### 一个PayPal API wrapper library

[https://github.com/nikosEfthias/paypal](https://github.com/nikosEfthias/paypal)

在Reddit上的讨论地址：[Read More](https://www.reddit.com/r/rust/comments/af5k82/i_have_just_released_a_paypal_api_wrapper_library/)

### Reddit 上关于 Windows GUI的讨论
回复中大概举了这些项目：

* [native-windows-gui](https://crates.io/crates/native-windows-gui)
* [azul](https://azul.rs)
* [charlesmine-rs](https://github.com/crlf0710/charlesmine-rs)

[Read More](https://www.reddit.com/r/rust/comments/af43dy/rust_windows_gui/)

### gfx-hal

gfx-rs的硬件抽象层

[https://github.com/gfx-rs/gfx](https://github.com/gfx-rs/gfx)

### dness:动态DNS客户端

[https://github.com/nickbabcock/dness](https://github.com/nickbabcock/dness)
